layout: "main"
logger: "file"
cache: 1
auto_page: 1
template: "template_toolkit"
charset: "utf8"
db_dbi: "dbi:SQLite:dbname="
db_name: "testing.db"
sql_schema: "SQL/schema.sql"
sql_fetch_all: "SQL/fetch_all.sql"

