layout: "main"
logger: "console"
cache: 1
auto_page: 1
charset: utf8
template: "template_toolkit"
db_dbi: "dbi:SQLite:dbname="
db_name: "pervomay.db"
sql_schema: "SQL/schema.sql"
sql_fetch_all: "SQL/fetch_all.sql"

